
language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install hexo -g
script:
  - hexo clean && hexo g

after_script:
  - cd public
  - git init
  - git config user.name "zhaohaibin"
  - git config user.email "zhaohaibin@outlook.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/cloudcube/cloudcube.github.io.git
   - secure: "mIDT1eR9WTjfpUr8cJKgFKe05TY3s+VhuI1tl6cthWLQGb6i/eqXIZQfLI0xFEj+mVnPdxqpekuzgkHJs05x0w908zFf/vaHgDs59LQSeow6ERBNlVQJgKwkRlFV1SPjId+kwNxyFqO+WHztMaCG6QTVYeT0NqqcUmhygL0kNObneByTxPabODW+61/Ekc7bYGgnaunsYQ8FoLrZKq6oJ9egn0zTohyz8hhnz2Otx+NlPRS41zcVbRUEU00/NlFqGkO3UjmHUp4mzY1pqQaC1D8rMYPw14bklG9O/MJNH4mO8QINY0hJZIh27E07pjiX/HyKWUQdk6yDZIhmX2CWGGNA5kiS8K0pAqTCfuWsctilIZDzwLh+LfEsEYMMVs5wsTUjfDGTl4DcDPJHyNg3lC//TvgNFAY6jAQ1dXPHhG0etoAS+4Jscn9yYatMtNPM/FimoUcov8E485lSGUDJNP7UVctJrI6SMg+0/5BpYZPtoNGBRjsn0uNm+8UOHBV/xmPSRc5i3p3Tl72rb8HQH2vTH4gEE04fYw5gVlKgimhA1R78v1aZMTNEUaZZ/8LDYwPysGqhB1uwy8xWlwmabSI1KxLQZ/6cuv0t4DXjo5sUZtf6MekZHwB6sCcYx8cFWmReh4x5kXdO2GGmdn84/aT4wqa6Q9rQhXajjn3+qE8="
